### ISSUE TITLE
Question on usage

### ISSUE THREAD

**Issue by jeff214103** [TimWhiting/dartros#26]
Hi there may I know if it is possible to give examples on basic ROS publisher and subscriber, that would able to communicate with the ROS Wiki basic python publisher and subscriber? I have found the code in example folder, is it possible to give it in README as well? So users may not need to go deep to the code for usage.

Also, I would like to ask about some details of usage.  For the code in example folder, there is List<String> args passing into it.  I have investigated into it and found it is about ROS ip, hostname etc.  Can you please provide the example of input, as well as the format of the input in the documentation as well?

Thank you so much

**Comment by TimWhiting** [comment]
The implementation is based off of rosnodejs. I can add in more documentation, but it really is quite similar to other ROS implementations, so it should be easy to pick up. The list of args passed into it is the same as you would have for any ROS node such as in C++. Feel free to create a pull request with anything you learn or find missing in the documentation. I'm happy to accept external contributions, since I don't have a ton of free time to work on this myself.

**Comment by jeff214103** [comment]
Ok I will take a look to that. Thank you so much for your information as I am actually new to ROS, that's help me a lot where to take reference to.  I lack experiences in ROS, and looking for some ROS Flutter communication library, so it is a bit difficult to understand the code.  However I really appreciate your work.
And I have notice one issue is that the dartgen message have pubspec.yaml conflicts with the library.  Is the dart gen yours as well?  
Also I am not able to find these (sensor_msgs, rosgraph_msgs, geometry_msgs, actionlib_msgs) libraries in pub dev.  Are they published or not yet? 
Thank you so much for your effort, and your time.

**Comment by TimWhiting** [comment]
Glad to know there are people interested in flutter + ros. dartgen is also my package, but should not generate message with pubspec.yaml conflicts, make sure you are using the nullsafety branch of that repository if you are using the null-safe version of dartros. As far as the standard messages (sensor_msgs, rosgraph_msgs, geometry_msgs, actionlib_msgs), they are published to pub.dev, but are hidden from the results (unlisted). So you should be able to use them in your pubspec.yaml. Since they are just message definitions, they do not have much in the way of documentation, and really the focus should be on dartros for documentation / pub.dev results, so I opted to remove them from the results of pub.dev, let me know if you think I should do otherwise.
